version: "3.5"

networks:
  jenkins-network:
    driver: bridge

services:
  bazel_cache:
    image: thelgevold/syntaxsuccess-bazel-cache
    container_name: bazel_cache
    networks:
      jenkins-network:
        aliases:
          - cache
    ports:
      - "9010:9010"
  jenkins:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"

    